title: Flux
author: ""

email: ""
description: "Electricity Flux is a website orientated around the energy transition in Great Britain and the engineering and policy required to achieve it."
baseurl: ""
url: "https://electricityflux.github.io"

theme: minima

plugins:
  - jekyll-feed
